from django.urls import path
from .views import (FederatedSearchView, ExpandQueryView, SaveRecordsView, DeduplicateRecordsView,
                    DashboardStatsView, ImportedRecordsView,
                    ScreeningPendingView, RctPredictView, RctDecisionView,
                    RctIncludedListView, PicoExtractView, PicoExtractGptView,
                    FulltextEligibleListView, FulltextScreenView, FulltextDecisionView,
                    FetchFullTextView, UploadFullTextPDFView,
                    ProjectListView, ProjectDetailView, ExportRctExcelView,
                    ExportRctScreeningExcelView, ExportFulltextScreeningExcelView,
                    RobAssessmentListView, RobSaveView, RobPredictView, RobPredictGptView, ExportRobExcelView)

urlpatterns = [
    path('federated_search/', FederatedSearchView.as_view(), name='federated_search'),
    path('expand_query/', ExpandQueryView.as_view(), name='expand_query'),
    path('save_records/', SaveRecordsView.as_view(), name='save_records'),
    path('deduplicate/', DeduplicateRecordsView.as_view(), name='deduplicate'),
    path('dashboard_stats/', DashboardStatsView.as_view(), name='dashboard_stats'),
    path('imported_records/', ImportedRecordsView.as_view(), name='imported_records'),
    path('screening_pending/', ScreeningPendingView.as_view(), name='screening_pending'),
    path('rct_predict/', RctPredictView.as_view(), name='rct_predict'),
    path('rct_decision/', RctDecisionView.as_view(), name='rct_decision'),
    path('rct_included/', RctIncludedListView.as_view(), name='rct_included'),
    path('pico_extract/', PicoExtractView.as_view(), name='pico_extract'),
    path('pico_extract_gpt/', PicoExtractGptView.as_view(), name='pico_extract_gpt'),
    path('fulltext_eligible/', FulltextEligibleListView.as_view(), name='fulltext_eligible'),
    path('fulltext_screen/', FulltextScreenView.as_view(), name='fulltext_screen'),
    path('fulltext_decision/', FulltextDecisionView.as_view(), name='fulltext_decision'),
    path('fetch_fulltext/', FetchFullTextView.as_view(), name='fetch_fulltext'),
    path('upload_fulltext_pdf/', UploadFullTextPDFView.as_view(), name='upload_fulltext_pdf'),
    path('projects/', ProjectListView.as_view(), name='project_list'),
    path('projects/<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('export_excel/', ExportRctExcelView.as_view(), name='export_excel'),
    path('export_rct_screening/', ExportRctScreeningExcelView.as_view(), name='export_rct_screening'),
    path('export_fulltext_screening/', ExportFulltextScreeningExcelView.as_view(), name='export_fulltext_screening'),
    path('rob_list/', RobAssessmentListView.as_view(), name='rob_list'),
    path('rob_save/', RobSaveView.as_view(), name='rob_save'),
    path('rob_predict/', RobPredictView.as_view(), name='rob_predict'),
    path('rob_predict_gpt/', RobPredictGptView.as_view(), name='rob_predict_gpt'),
    path('export_rob/', ExportRobExcelView.as_view(), name='export_rob'),
]
