# Generated by Django 4.2.29 on 2026-03-13 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiteratureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_db', models.CharField(choices=[('PubMed', 'PubMed'), ('Embase', 'Embase'), ('Cochrane', 'Cochrane Library'), ('KMbase', 'KMbase'), ('RISS', 'RISS'), ('CNKI', 'CNKI'), ('Other', 'Other')], default='Other', max_length=20)),
                ('title', models.TextField()),
                ('abstract', models.TextField(blank=True, null=True)),
                ('authors', models.TextField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, max_length=512, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('pmid', models.CharField(blank=True, max_length=100, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('IMPORTED', 'Imported'), ('DEDUP_REVIEW', 'Pending Deduplication Review'), ('DEDUP_REJECTED', 'Rejected as Duplicate'), ('SCREENING_PENDING', 'Pending Screening'), ('RCT_INCLUDED', 'Included as RCT'), ('RCT_EXCLUDED', 'Excluded (Not RCT)'), ('EXTRACTED', 'PICO Extracted')], default='IMPORTED', max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='search.searchproject')),
            ],
        ),
    ]
