# Generated by Django 4.2.5 on 2026-03-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturerecord',
            name='exclusion_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='literaturerecord',
            name='reviewer_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='literaturerecord',
            name='status',
            field=models.CharField(choices=[('IMPORTED', 'Imported'), ('DEDUP_REVIEW', 'Pending Deduplication Review'), ('DEDUP_REJECTED', 'Rejected as Duplicate'), ('SCREENING_PENDING', 'Pending Screening'), ('RCT_INCLUDED', 'Included as RCT'), ('RCT_EXCLUDED', 'Excluded (Not RCT)'), ('FULLTEXT_INCLUDED', 'Included (Full-text)'), ('FULLTEXT_EXCLUDED', 'Excluded (Full-text)'), ('EXTRACTED', 'PICO Extracted')], default='IMPORTED', max_length=30),
        ),
    ]
