# Generated by Django 4.2.5 on 2026-03-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_literaturerecord_exclusion_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturerecord',
            name='full_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
