# Generated by Django 4.2.5 on 2026-03-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_literaturerecord_full_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturerecord',
            name='pico_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
