# Generated by Django 4.2.5 on 2026-03-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_literaturerecord_pico_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturerecord',
            name='rob_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='literaturerecord',
            name='status',
            field=models.CharField(choices=[('IMPORTED', 'Imported'), ('DEDUP_REVIEW', 'Pending Deduplication Review'), ('DEDUP_REJECTED', 'Rejected as Duplicate'), ('SCREENING_PENDING', 'Pending Screening'), ('RCT_INCLUDED', 'Included as RCT'), ('RCT_EXCLUDED', 'Excluded (Not RCT)'), ('FULLTEXT_INCLUDED', 'Included (Full-text)'), ('FULLTEXT_EXCLUDED', 'Excluded (Full-text)'), ('EXTRACTED', 'PICO Extracted'), ('ROB_COMPLETED', 'ROB Assessment Completed')], default='IMPORTED', max_length=30),
        ),
    ]
