# Generated by Django 4.2.5 on 2026-03-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_literaturerecord_rob_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturerecord',
            name='rob_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='literaturerecord',
            name='rob_last_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
