# Generated by Django 4.2.5 on 2026-03-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_literaturerecord_rob_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturerecord',
            name='pico_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='literaturerecord',
            name='pico_last_extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
